### ISSUE TITLE
[CI] Protect main branch

### ISSUE THREAD

**Issue by eforgacs** [PLAIF-dev/sw_wpf_example#3]
### 설명

GitHub 저장소의 메인 브랜치는 직접 푸시로부터 보호되어야 하는 이유는 여러 가지가 있습니다. 먼저, 메인 브랜치는 프로젝트의 핵심 브랜치로, 안정적이고 신뢰할 수 있는 코드만 포함되어야 합니다. 이 브랜치는 보통 최종 사용자나 프로덕션 환경에서 사용되기 때문에, 안정성이 매우 중요합니다.

직접 푸시를 허용하지 않음으로써, 모든 코드 변경은 리뷰 과정을 거쳐야만 메인 브랜치에 병합될 수 있습니다. 이런 리뷰 과정은 코드의 품질을 유지하고, 버그를 사전에 발견하며, 보안 문제를 미연에 방지하는 데 도움이 됩니다. 또한, 이 과정을 통해 팀 내의 지식 공유가 이루어지고, 팀원 간의 코드 이해도가 향상됩니다.

팀원이 실수로 중요한 변경을 직접 메인 브랜치에 푸시하는 것을 막음으로써, 예기치 않은 오류나 시스템 다운 등의 위험을 줄일 수 있습니다. 또한, 브랜치 보호 규칙을 설정함으로써 자동화된 테스트가 통과되지 않는 코드의 병합을 막을 수 있으며, 이는 전체적인 프로젝트 안정성에 기여합니다.

결국, 메인 브랜치를 보호하는 것은 프로젝트의 안정성과 품질을 유지하기 위해 필수적인 조치입니다. 모든 코드 변경이 철저히 검토되고 검증되어야 하며, 이는 프로젝트의 성공을 위한 중요한 단계입니다.

**Comment by powerstrong** [comment]
I did it! Now we need to get at least 1 approval before merge the PR. Applied to `main` branch. 😄

**Comment by eforgacs** [comment]
> I did it! Now we need to get at least 1 approval before merge the PR. Applied to `main` branch. 😄

Thanks a lot! [🙌](https://emojipedia.org/raising-hands) There's a few other repos for which I want to do this same thing - as I've discovered them, I've been creating duplicate copies of this issue.
